[package]
name = "color_converter"
version = "0.1.0"
authors = ["Patrick Jahnig <psj516@vt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.4"
regex = "1.3.4"
structopt = "0.3.9"
